### ISSUE TITLE
Model fine-tuning

### ISSUE THREAD

**Issue by dbalabka** [OPHoperHPO/image-background-remove-tool#116]
Thanks for your effort in creating such an incredible tool! We have evaluated the development branch changes and see significant improvement in background removing quality using the Tracer B7 model. Still, I assume there might be more accurate results by applying fine-tuning for some specific domain images. Therefore I would like to ask a few questions:
1. Did you have experience in fine-tuning the Tracer B7 model? 
2. Does the fine-tuning improve the quality of background removal for some specific domains?
3. Are you going to implement any possibility to fine-tune supported models U2 Net and Tracer B7?

**Comment by OPHoperHPO** [comment]
Hello @dbalabka

Yes, fine-tuning the Tracer will improve the quality of segmentation on problem domains, where there are small or medium defects in cutting out the desired area due to the lack of objects of this domain in the training set for the general model, but the success of fine-tuning depends heavily on the similarity of the domain to others, already built into the model and the amount of training data for finetuning. Need more information to be more specific. 
We plan to implement Tracer finetuning utilities in the near future. U2Net networks and others are marked as deprecated, which means that tools for them will not be added. In one of the next releases, we will implement a new network for hair-like objects, better than u2net.
