### ISSUE TITLE
how to specify a target area to keep when there are multiple objects in image?

### ISSUE THREAD

**Issue by kaka1909** [OPHoperHPO/image-background-remove-tool#124]
Thank you for the awesome project!!! 

I got a question as title said. I'm wondering if there is an image with multiple people and objects, and I want to specify one of them to keep, and others could be removed along with the background, how can I achieve that with this tool? 

I came up with a thought that add keeping coordinates args and process the image before preprocessing. But I don't know if this will influence the removing effect as there are much info loss after image crop. 

Thanks~

**Comment by OPHoperHPO** [comment]
Hello @kaka1909 
At the moment this functionality is difficult to implement in the project. This can probably be done with yolov4 and the bounds of the objects it returns. Or change the architecture of the segmentation neural network so that it can segment objects by class. There are many solutions on github that segment objects according to points previously marked by a person, probably integrating them into this project can solve your problem

**Comment by kaka1909** [comment]
> Hello @kaka1909 At the moment this functionality is difficult to implement in the project. This can probably be done with yolov4 and the bounds of the objects it returns. Or change the architecture of the segmentation neural network so that it can segment objects by class. There are many solutions on github that segment objects according to points previously marked by a person, probably integrating them into this project can solve your problem

Thank you for quick reply.  As you said, I will try to use yolov4 to identify the objects in image, and offer user in frontend to specify an area to keep, and then accept the mask file and move masked area pixels to new image, then pass new image to carve-kit to do the rest works. If it worked well, I will try to integrate it into this project. Just a little concern if this feature matched with your system design.

**Comment by kaka1909** [comment]
Additionally, I really like your coding style, pretty comfortable to read. Clean and neat. 👍
