### ISSUE TITLE
Not fully removed background - what could we do ? 

### ISSUE THREAD

**Issue by yncki** [OPHoperHPO/image-background-remove-tool#13]
Input
![Best-Girls-Bikes-Guardian](https://user-images.githubusercontent.com/1530496/84551214-2f6bde80-ad0d-11ea-95a1-c82b49a80db4.jpg)

output ( u2net ) 
![bgremove3](https://user-images.githubusercontent.com/1530496/84551226-38f54680-ad0d-11ea-8bed-16982a4d395f.png)

**Comment by OPHoperHPO** [comment]
You can use two neural networks in order to first detect the boundaries of objects in a photograph, cut them out, sequentially remove the background from each object in turn and subsequently collect the whole image from them back. 
__[Here](https://colab.research.google.com/gist/OPHoperHPO/bfc8423c21d24f76356a9dee15ee7aae/rm_bg_fastrcnn_alpha.ipynb)   you can test the algorithm described above.__


Output(u2net + fastrcnn)
![2](https://user-images.githubusercontent.com/29470622/84563745-ee250e80-ada0-11ea-80bc-93ef810d5afc.png)
