### ISSUE TITLE
Beginner Questions and Comments

### ISSUE THREAD

**Issue by john-davies** [OPHoperHPO/image-background-remove-tool#26]
I'm investigating using `image-background-remove-tool` in some photogrammetry that I'm doing. I've had a quick test and it seems to work quite well but I have a few questions and comments:

1. The install went fine but under Ubuntu 16.04 I had to change the `setup.sh` to explicitly refer to `python3` as the default `python` command refers to the version 2.7 install. Obviously I could change this but I'm concerned about breaking other things.

2. If I run the tool on a directory then I get error messages if that directory contains sub-directories or non-image files ( I'm not 100% sure about this though ). Is it possible to put an input file specifier like `*.jpg` so that sub directories and other files are ignored?

3. The output file file format is png. Is it possible to use jpg instead? The conversion to png loses the EXIF data which is necessary for the photogrammetry process to work properly. It's not a major issue as I can write a script to copy the EXIF data from the original images using 'exiftool`.

Apologies if these are obvious questions but I'm not familiar with Python. However it looks like a really good tool and I'm going to investigate in more detail.

**Comment by OPHoperHPO** [comment]
Hello, @john-davies 

1)It was a bug.  Replacing the name of the python executable, you fixed it. There was nothing disturbed in the program.

2) And this is also a bug.  I will fix it in a new release soon.  Unfortunately, the program does not yet support the option of processing all files with a specific extension, but soon such functionality will be added.

3) JPEG format cannot be used, since images in this format do not support alpha channel (transparency).  JPEG can be used if you do not need transparency and you are satisfied with a white or black background in those places where there was transparency.  Transferring EXIF ​​to png is not possible because PNG does not support exif.

**Comment by john-davies** [comment]
Points 1 & 2: Thanks

Point 3: OK, I understand.  For my application it's not really a problem and I use the following workflow, assuming that the original files are in a subdirectory called "original" and the ones with the background removed in a subdirectory called "bg_remove" 

**Imagemagick to convert to jpg:**
`mogrify -format jpg -background <colour> -alpha remove -path . bg_removal/*.png`
_( sometimes it's useful to change the background colour from the default black )_

**Restore EXIF data:**
`for f in *.jpg; do exiftool -tagsFromFile original/"$f" "$f"; done`

**Comment by Vickyilango** [comment]
Hey, How to estimate the uncertainty, in some images its not segmenting good so i wanted to know is there a way to gets its estimate or success percentage so that i can review those images alone.
