### ISSUE TITLE
Post-processing methods takes too much time when processing high resolution images

### ISSUE THREAD

**Issue by muhammadabdullah34907** [OPHoperHPO/image-background-remove-tool#29]
Hi @OPHoperHPO 
   Thank you for amazing work. I have some questions.

1. why all post-processing model takes too much time on high resolution images. ?
2. how to decrease this time if there is any postprocessing related to opencv or anything other than rtb-bnb model prediction ?

**Comment by OPHoperHPO** [comment]
Hello, @muhammadabdullah34907. 

Responses:
1) Image post-processing methods take a very long time when processing high resolution images (more than 1500x1500) solely due to non-performance optimized code, in particular the `__remove_too_transparent_borders__` function, etc.

2) You can reduce this time in the following ways:
	- Wait for the next release of this tool.
	- Manually optimize the code in` postprocessing.py `, for example, try to replace loops in a function
	`__remove_too_transparent_borders__` to call the `where` function from the `numpy/cupy` module.
	- Try to run this code in cython.
