### ISSUE TITLE
Thank you, the future, and EC2 instances.

### ISSUE THREAD

**Issue by qarthandgi** [OPHoperHPO/image-background-remove-tool#34]
Hey @OPHoperHPO, first want to say thank you for the amazing amount of work that you've put into this! I had two questions for you in regards to this amazing journey you've embarked on.

1. What are your long term intentions with this project, and do you have a rough timeline for new releases/features?
2. Do you have a specific EC2 instance type that you recommend to use with this workload?

**Comment by OPHoperHPO** [comment]
Hi, @qarthandgi.

**I)** I plan to develop this project further.
Also, I plan to:

1) Add new methods of preprocessing or post-processing images / neural networks that will improve the quality of background removal.
2) Improve the quality of the source code of this project.
3) Train my own models for neural networks that were used to remove the background.
4) Add support for multi-gpu acceleration.
5) Add support for automatic color correction at the edges of the image.
6) Develop web service for free and easy use of this tool, when i will can  pay  rent  for computing power of instances for this web service.
7) Add to the GUI the possibility for post-editing images after removing the background, for example, to change background of this image or add/remove some parts of the image on the final image.


**I.1)** About the schedule of new releases or features.
I don't have a stable release schedule for new releases / features right now, because I'm working on this project alone. And it is difficult for me alone to maintain any stable schedule, since this project is not my main activity and I spend my personal free time on this project, which, alas, is very small, because I am also a person and I have my own affairs, worries and studying at the university. Therefore, as long as there are no other developers in the project interested in its development or active sponsors who support the development of the project financially, thanks to which I could make my project my main activity, a stable schedule for the release of updates is impossible.

**II)** I don't use any Amazon EC2 instances before this time, but i looked at the types of instances on Amazon website.
I recommend you to use the instance with 1 modern and powerful gpu and 8 GB of ram. So you can use P2 or P3 or G4 or G3 instances.

**Comment by pixamora** [comment]
Thank you for the clear insight and information @OPHoperHPO! Your work is appreciated and valued. Are you pursuing computer science at university, and is computer vision/AI your main passion?

**Comment by qarthandgi** [comment]
Thank you for the clear insight and information @OPHoperHPO! Your work is appreciated and valued. Are you pursuing computer science at university, and is computer vision/AI your main passion?

**Comment by OPHoperHPO** [comment]
> Thank you for the clear insight and information @OPHoperHPO! Your work is appreciated and valued. Are you pursuing computer science at university, and is computer vision/AI your main passion?

Yes.

**Comment by MaickDavila** [comment]
@OPHoperHPO  Hello friend, I am a university student and I am using your project for a course, I like your work and I would be willing in the company of a friend to support you, we would like to contact you and talk about the subject.

**Comment by OPHoperHPO** [comment]
> @OPHoperHPO  Hello friend, I am a university student and I am using your project for a course, I like your work and I would be willing in the company of a friend to support you, we would like to contact you and talk about the subject.


Hello @MaickDavila, 

You can find my contacts at my GitHub profile page. 
I will duplicate them again here.

My contacts:
Email: farvard34 [AT] gmail.com (replace "[AT]" to "@")
Telegram: @Anodev1

**Comment by dheerajmartpe** [comment]
Hey @OPHoperHPO Do you have any updates on this project for betterment like adding pre/post processing for better quality of the images? I would be glad to know about any further work you have made to this. If you don't, let me know, we can start working on this again. Thanks!

**Comment by OPHoperHPO** [comment]
> Hello @OPHoperHPO I wanted to inquire if there have been any recent updates or progress on this project, specifically concerning improvements in image quality through the implementation of pre- and post-processing techniques. I'm keen to learn about any advancements or additional work that has been done in this area. If there haven't been recent developments, I'm open to discussing and collaborating on this aspect further. Thanks!

I answered you on Telegram.

**Comment by dheerajmartpe** [comment]
@OPHoperHPO Great, I appreciate an update on the bug fix you're working on. Whenever you have a moment, please share the details of the update. I'd be happy to use it for my project and upgrade it. Thanks!
