### ISSUE TITLE
How to save output images to JPEG?

### ISSUE THREAD

**Issue by likeoff** [OPHoperHPO/image-background-remove-tool#39]
Which parameter should I add to CLI to export in JPEG with high quality?

**Comment by OPHoperHPO** [comment]
Hi @likeoff 

Unfortunately, the program cannot save images in JPEG format, because JPEG format cannot contain information about the transparency of the image. Technically, you can modify program to save output images in JPEG format, but then all transparency will be replaced with a white or black background.
