### ISSUE TITLE
Running on MacOs

### ISSUE THREAD

**Issue by Defuera** [OPHoperHPO/image-background-remove-tool#4]
Running on mac os gives an error

```
I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f91b4835560 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Error! Please indicate the correct extension of the final file, for example: .png Error:  cannot write mode RGBA as JPEG
```

Please advice if it's possible to run on mac os?

**Comment by OPHoperHPO** [comment]
Officially, the program **does not support Mac OS**, but **theoretically it can work on this platform**.  Write with what arguments you run the program.  The log shows that you specified the extension of the output file incorrectly, namely, you specified the `.jpeg` or `.jpg` extension for the output file, which is *"completely wrong**, since a JPEG image cannot contain an alpha channel, therefore, as an extension for the output file, you should use  **only** ``.png`` format.

**Comment by Defuera** [comment]
oh, yes, with .png it worked, thx!
